language: python

python:
  - "3.4"


before_install:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install -y python3.3


install:
  - pip install -r requirements-dev.txt

script:
  - tox


cache: apt